version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 17
    commands:
      - npm install -g yarn
      - yarn install

  build:
    commands:
      - yarn build

artifacts:
  files:
    - build/**/*