version: 0.2

env:
  variables:
    NODE_OPTIONS: "--openssl-legacy-provider"
    
phases:
  install:
    commands:
      - n latest
      - npm install -g yarn
      - yarn install

  build:
    commands:
      - yarn build

artifacts:
  files:
    - build/**/*